### ISSUE TITLE
Missing Post

### ISSUE THREAD

**Issue by inertia186** [SteemData/steemdata.com#1]
I found an example of a post that has not been ingested.

```javascript
db.getCollection('Posts').find({author: 'swolesome'}).sort({_id: -1})
```

https://steemit.com/@swolesome

The post that didn't get ingested is:

https://steemd.com/steemdev/@swolesome/ned-has-spoken-promoting-steem-through-card-tournaments-and-basketball

**Comment by Netherdrake** [comment]
I checked, and the post is there.

You might want to sort by post creation time, to get newest posts, like so:
```javascript
db.getCollection('Posts').find({author: 'swolesome'}).sort({created: -1})
```
